# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Build
      run: dotnet build
    - name: Build Release
      run: dotnet build -c Release
    - name: Build Release SelfContainer
      run: dotnet build -c Release -r linux-x64 --self-contained true
    - name: Publish Release SelfContainer
      run: dotnet publish -c Release -r linux-x64 --self-contained true
